/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at
 * src/com/vodafone360/people/VODAFONE.LICENSE.txt or
 * http://github.com/360/360-Engine-for-Android
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each file and
 * include the License file at src/com/vodafone360/people/VODAFONE.LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the fields
 * enclosed by brackets "[]" replaced with your own identifying information:
 * Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 *
 * Copyright 2010 Vodafone Sales & Services Ltd.  All rights reserved.
 * Use is subject to license terms.
 */

package com.vodafone360.people.datatypes;

import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Vector;

/**
 * BaseDataType encapsulating an Comment retrieved from, or to be issued to, Now
 * + server
 */
public class Comment extends BaseDataType {

	public Long mCommentId = null;
	public EntityKey mEntityKey = null;
	public String mText = null;
	public Boolean mInappropriate = null;
	public String mExtCommentId = null;

	/**
	 * Tags associated with Comment representing data items associated with
	 * Comment returned from server.
	 */
	public enum Tags {
		COMMENT_ID("commentid"), ENTITY_KEY("entitykey"), TEXT("text"), INAPPROPRIATE(
				"inappropriate"), EXT_COMMENT_ID("extcommentid");

		private final String tag;

		/**
		 * Constructor creating Tags item for specified String.
		 * 
		 * @param s
		 *            String value for Tags item.
		 */
		private Tags(String s) {
			tag = s;
		}

		/**
		 * String value associated with Tags item.
		 * 
		 * @return String value for Tags item.
		 */
		private String tag() {
			return tag;
		}

		/**
		 * Find Tags item for specified String.
		 * 
		 * @param tag
		 *            String value to find Tags item for
		 * @return Tags item for specified String, null otherwise
		 */
		private static Tags findTag(String tag) {
			for (Tags tags : Tags.values()) {
				if (tag.compareTo(tags.tag()) == 0) {
					return tags;
				}
			}
			return null;
		}
	}

	/*private Tags findTag(String tag) {
		for (Tags tags : Tags.values()) {
			if (tag.compareTo(tags.tag()) == 0) {
				return tags;
			}
		}
		return null;
	}*/

	/**
	 * Sets the value of the member data item associated with the specified tag.
	 * 
	 * @param tag
	 *            Current tag
	 * @param value
	 *            Value associated with the tag
	 * @return void
	 */
	@SuppressWarnings("unchecked")
	private void setValue(Tags tag, Object value) {
		if (tag != null) {
			switch (tag) {
			case COMMENT_ID:
				mCommentId = (Long) value;
				break;

			case ENTITY_KEY:
				Vector<Hashtable<String, Object>> v = (Vector<Hashtable<String, Object>>) value;
				for (Hashtable<String, Object> hash : v) {
					EntityKey entityKey = new EntityKey();
					entityKey.createFromHashtable(hash);
					mEntityKey = entityKey;
				}
				break;

			case TEXT:
				mText = (String) value;
				break;

			case INAPPROPRIATE:
				mInappropriate = (Boolean) value;
				break;

			case EXT_COMMENT_ID:
				mExtCommentId = (String) value;
				break;

			default:
				// Do nothing.
				break;
			}
		}
	}

	/**
	 * Create Comment from HashTable generated by Hessian-decoder
	 * 
	 * @param Hashtable representing Comment Item
	 * @return Comment created from Hashtable
	 */
	static public Comment createFromHashtable(Hashtable<String, Object> hash) {
		Comment comment = new Comment();
		Enumeration<String> e = hash.keys();
		while (e.hasMoreElements()) {
			String key = e.nextElement();
			Object value = hash.get(key);
			Tags tag = Tags.findTag(key);
			comment.setValue(tag, value);
		}
		return comment;
	}

	/**
	 * Create Hashtable from Comments parameters.
	 * 
	 * @param none
	 * @return Hashtable generated from Comments parameters.
	 */
	public Hashtable<String, Object> createHashtable() {
		Hashtable<String, Object> htab = new Hashtable<String, Object>();

		if (mCommentId != null) {
			htab.put(Tags.COMMENT_ID.tag(), mCommentId);
		}
		if (mEntityKey != null) {
			Vector<Object> v = new Vector<Object>();
			v.add(mEntityKey.createHastable());
			htab.put(Tags.ENTITY_KEY.tag(), v);
		}
		if (mText != null) {
			htab.put(Tags.TEXT.tag(), mText);
		}
		if (mInappropriate != null) {
			htab.put(Tags.INAPPROPRIATE.tag(), mInappropriate);
		}
		if (mExtCommentId != null) {
			htab.put(Tags.EXT_COMMENT_ID.tag(), mExtCommentId);
		}
		return htab;
	}

	@Override
	public int getType() {
		return COMMENTS_DATATYPE;
	}
}
