package com.vodafone360.people.datatypes;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.List;
import java.util.Vector;

import com.vodafone360.people.utils.LogUtils;



public class GroupIdListResponse extends BaseDataType  {

	/**
     * Tags associated with AlbumListResponse item.
     */
    private enum Tags {
        ITEM("item"),
        STAT("stat"),
        ERR("err"),
        CODE("code");

        private final String tag;

        /**
         * Construct Tags item from supplied String
         * 
         * @param s String value for Tags item.
         */
        private Tags(String s) {
            tag = s;
        }

        /**
         * String value for Tags item.
         * 
         * @return String value for Tags item.
         */
        private String tag() {
            return tag;
        }
    }
    
    /**
     * Find Tags item for specified String
     * 
     * @param tag String value to find Tags item for
     * @return Tags item for specified String, null otherwise
     */
    private Tags findTag(String tag) {
        for (Tags tags : Tags.values()) {
            if (tag.compareTo(tags.tag()) == 0) {
                return tags;
            }
        }
        return null;
    }
    
    public Long mItem = null;

    public String mStat = null;
    
    public String mErr = null;
    
    public String mCode = null;
    
    /**
     * Create GroupIdList from Hashtable generated by Hessian-decoder
     * 
     * @param hash Hashtable containing GroupIdList parameters
     * @return GroupIdList created from hashtable
     */
    public GroupIdListResponse createFromHashTable(Hashtable<String, Object> hash) {

        Enumeration<String> e = hash.keys();
        while (e.hasMoreElements()) {
            String key = e.nextElement();
            LogUtils.logE("Key:"+key);
            Tags tag = findTag(key);
            setValue(tag, hash.get(key));
        }
        return this;
    }
    
    /**
     * Sets the value of the member data item associated with the specified tag.
     * 
     * @param tag Current tag
     * @param value Value associated with the tag
     */
    @SuppressWarnings("unchecked")
	private void setValue(Tags tag, Object value) {
        switch (tag) {
            case ITEM:
                if (mItem == null) {
                	mItem = (Long) value;
                }
                break;
            case STAT:
                if (mStat == null) {
                	mStat = (String)value;
                }
                break;
            case ERR:
                if (mErr == null) {
                	mErr = (String)value;
                }
                break;
                
            case CODE:
                if (mCode == null) {
                	mCode = (String)value;
                }
                break;
            default:
                break;
        }
    }

	@Override
	public int getType() {
		return GROUP_ID_LIST_DATATYPE;
	}

}
