package com.vodafone360.people.datatypes;

import java.util.Enumeration;
import java.util.Hashtable;

import android.util.Log;


public class IdentityText extends BaseDataType{
	
	
	public String mText = null;
	public String mNetwork = null;

	/**
     * Tags associated with IdentityText representing data items associated with
     * IdentityText returned from server.
     */
    public enum Tags {
        TEXT("text"),
        NETWORK("network");

        private final String tag;

        /**
         * Constructor creating Tags item for specified String.
         * 
         * @param s String value for Tags item.
         */
        private Tags(String s) {
            tag = s;
        }

        /**
         * String value associated with Tags item.
         * 
         * @return String value for Tags item.
         */
        private String tag() {
            return tag;
        }

        /**
         * Find Tags item for specified String.
         * 
         * @param tag String value to find Tags item for
         * @return Tags item for specified String, null otherwise
         */
        private static Tags findTag(String tag) {
            for (Tags tags : Tags.values()) {
                if (tag.compareTo(tags.tag()) == 0) {
                    return tags;
                }
            }
            return null;
        }
    }
    
    /**
     * Sets the value of the member data item associated with the specified tag.
     * 
     * @param tag Current tag
     * @param val Value associated with the tag
     */
    private void setValue(Tags tag, Object value) {
        if (tag != null) {
            switch (tag) {
                case TEXT:
                    mText = (String)value;
                    break;
                case NETWORK:
                    mNetwork = (String)value;
                    break;
                

                default:
                    // Do nothing.
                    break;
            }
        }
    }

	 /**
     * Create IdentityText from HashTable generated by Hessian-decoder
     * 
     * @param hash Hashtable representing IdentityText
     * @return IdentityText created from Hashtable
     */
    static public IdentityText createFromHashtable(Hashtable<String, Object> hash) {
    	IdentityText identityText = new IdentityText();
        Enumeration<String> e = hash.keys();
        while (e.hasMoreElements()) {
            String key = e.nextElement();
            Object value = hash.get(key);
            Log.d("Comment", "createFromHashtable: Key " + key + "value: " + value);
            Tags tag = Tags.findTag(key);
            identityText.setValue(tag, value);
        }
        return identityText;
    }
    
    /**
     * Create Hashtable from IdentityText parameters.
     * 
     * @return Hashtable generated from IdentityText parameters.
     */
    public Hashtable<String, Object> createHashtable() {
        Hashtable<String, Object> htab = new Hashtable<String, Object>();

        if (mText != null) {
            htab.put(Tags.TEXT.tag(), mText);
        }
        if (mNetwork != null) {
        	 htab.put(Tags.NETWORK.tag(), mNetwork);
        }
        return htab;
    }

	@Override
	public int getType() {
		// TODO Auto-generated method stub
		return IDENTITY_TEXT_RESPONSE;
	}
}
