
/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at
 * src/com/vodafone360/people/VODAFONE.LICENSE.txt or
 * http://github.com/360/360-Engine-for-Android
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each file and
 * include the License file at src/com/vodafone360/people/VODAFONE.LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the fields
 * enclosed by brackets "[]" replaced with your own identifying information:
 * Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 *
 * Copyright 2010 Vodafone Sales & Services Ltd.  All rights reserved.
 * Use is subject to license terms.
 */

package com.vodafone360.people.datatypes;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.List;
import java.util.Vector;

/**
 * BaseDataType encapsulating trackIds of Downloadable Music Tracks for the user retrieved from Now
 * + server
 */
public class MusicDownloadableTrack extends BaseDataType {

	public Boolean success = null;
	public String resultCode = "";
	public List<String> trackIdList = new ArrayList<String>();
	
	@Override
	public String toString() {
		String str = success + ", " + resultCode + ", " + trackIdList.toString();
		return str;
	}
	
	/**
	 * Tags associated with Downloadable Music Tracks representing data items associated with
	 * it returned from server. 
	 * 
	 */
	public enum Tags {
		SUCCESS("success"), 
		RESULT_CODE("resultcode"), 
		TRACK_ID_LIST("trackidlist");

		private final String tag;

		/**
		 * Constructor creating Tags item for specified String.
		 * 
		 * @param s
		 *            String value for Tags item.
		 */
		private Tags(String s) {
			tag = s;
		}

		/**
		 * String value associated with Tags item.
		 * 
		 * @return String value for Tags item.
		 */
		private String tag() {
			return tag;
		}

		/**
		 * Find Tags item for specified String.
		 * 
		 * @param tag
		 *            String value to find Tags item for
		 * @return Tags item for specified String, null otherwise
		 */
		private static Tags findTag(String tag) {
			for (Tags tags : Tags.values()) {
				if (tag.compareTo(tags.tag()) == 0) {
					return tags;
				}
			}
			return null;
		}
	}

	/**
	 * Sets the value of the member data item associated with the specified tag.
	 * 
	 * @param tag
	 *            Current tag
	 * @param val
	 *            Value associated with the tag
	 * @return void
	 */
	@SuppressWarnings("unchecked")
	private void setValue(Tags tag, Object value) {
		if (tag != null) {
			switch (tag) {
			case SUCCESS:
				success = (Boolean) value;
				break;
			case RESULT_CODE:
				resultCode = (String) value;
				break;
			case TRACK_ID_LIST:
				Vector<String> vals = (Vector<String>)value;
				for (String trackIds : vals) {
					trackIdList.add(trackIds);
				}
				break;
			default:
				// Do nothing.
				break;
			}
		}
	}

	/**
	 * Create Items from HashTable generated by Hessian-decoder
	 * 
	 * @param hash Hashtable representing ActivityItem
	 * @return MusicPurchasedTracks created from Hashtable
	 * 
	 **/
	public MusicDownloadableTrack createFromHashtable(Hashtable<String, Object> hash) {
		MusicDownloadableTrack tracks = new MusicDownloadableTrack();
		Enumeration<String> e = hash.keys();
		
		while (e.hasMoreElements()) {
			String key = e.nextElement();
			Object value = hash.get(key);
			
			
			Tags tag = Tags.findTag(key);
			tracks.setValue(tag, value);
		}
		return tracks;
	}

	/**
	 * Create Hashtable from MusicDownloadableTrack parameters.
	 * 
	 * @param none
	 * @return Hashtable generated from MusicPurchasedTrack parameters.
	 */
	public Hashtable<String, Object> createHashtable() {
		Hashtable<String, Object> htab = new Hashtable<String, Object>();

		if (success != null) {
			htab.put(Tags.SUCCESS.tag(), success);
		}
		if (resultCode != null) {
			htab.put(Tags.RESULT_CODE.tag(), resultCode);
		}
		if (trackIdList != null) {
			Vector<String> vL = new Vector<String>();
            for (String l : trackIdList) {
                vL.add(l);
            }
            htab.put(Tags.TRACK_ID_LIST.tag(), vL);
		}
		return htab;
	}

	@Override
	public int getType() {
		return DOWNLOADABLE_MUSIC;
	}
}
