
/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at
 * src/com/vodafone360/people/VODAFONE.LICENSE.txt or
 * http://github.com/360/360-Engine-for-Android
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each file and
 * include the License file at src/com/vodafone360/people/VODAFONE.LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the fields
 * enclosed by brackets "[]" replaced with your own identifying information:
 * Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 *
 * Copyright 2010 Vodafone Sales & Services Ltd.  All rights reserved.
 * Use is subject to license terms.
 */

package com.vodafone360.people.datatypes;

import java.util.Enumeration;
import java.util.Hashtable;

/**
 * BaseDataType encapsulating DD for Music Track retrieved from Now + server
 */
public class MusicDDForTrack extends BaseDataType {

	public String ddResultCode = "";
	public String ddResultText = "";
	public String downloadDescriptor = "";
	
	/**
	 * Tags associated with Downloadable Music Tracks representing data items associated with
	 * it returned from server. 
	 * 
	 */
	public enum Tags {
		DD_RESULT_CODE("ddresultcode"), 
		DD_RESULT_TEXT("ddresulttext"), 
		DOWNLOAD_DESCRIPTOR("downloaddescriptor");

		private final String tag;

		/**
		 * Constructor creating Tags item for specified String.
		 * 
		 * @param s
		 *            String value for Tags item.
		 */
		private Tags(String s) {
			tag = s;
		}

		/**
		 * String value associated with Tags item.
		 * 
		 * @return String value for Tags item.
		 */
		private String tag() {
			return tag;
		}

		/**
		 * Find Tags item for specified String.
		 * 
		 * @param tag
		 *            String value to find Tags item for
		 * @return Tags item for specified String, null otherwise
		 */
		private static Tags findTag(String tag) {
			for (Tags tags : Tags.values()) {
				if (tag.compareTo(tags.tag()) == 0) {
					return tags;
				}
			}
			return null;
		}
	}

	/**
	 * Sets the value of the member data item associated with the specified tag.
	 * 
	 * @param tag
	 *            Current tag
	 * @param val
	 *            Value associated with the tag
	 * @return void
	 */
	private void setValue(Tags tag, Object value) {
		if (tag != null) {
			switch (tag) {
			case DD_RESULT_CODE:
				ddResultCode = (String) value;
				break;
			case DD_RESULT_TEXT:
				ddResultText= (String) value;
				break;
			case DOWNLOAD_DESCRIPTOR:
				downloadDescriptor= (String)value;
				break;
			default:
				// Do nothing.
				break;
			}
		}
	}

	/**
	 * Create Items from HashTable generated by Hessian-decoder
	 * 
	 * @param hash Hashtable representing ActivityItem
	 * @return DD for Music Track created from Hashtable
	 * 
	 **/
	public MusicDDForTrack createFromHashtable(Hashtable<String, Object> hash) {
		MusicDDForTrack tracks = new MusicDDForTrack();
		Enumeration<String> e = hash.keys();
		while (e.hasMoreElements()) {
			String key = e.nextElement();
			Object value = hash.get(key);
			Tags tag = Tags.findTag(key);
			tracks.setValue(tag, value);
		}
		return tracks;
	}

	/**
	 * Create Hashtable from MusicPurchasedTrack parameters.
	 * 
	 * @param none
	 * @return Hashtable generated from MusicPurchasedTrack parameters.
	 */
	public Hashtable<String, Object> createHashtable() {
		Hashtable<String, Object> htab = new Hashtable<String, Object>();

		if (ddResultCode != null) {
			htab.put(Tags.DD_RESULT_CODE.tag(), ddResultCode);
		}
		if (ddResultText != null) {
			htab.put(Tags.DD_RESULT_TEXT.tag(), ddResultText);
		}
		if (downloadDescriptor!= null) {
			htab.put(Tags.DOWNLOAD_DESCRIPTOR.tag(), downloadDescriptor);
		}
		return htab;
	}

	@Override
	public int getType() {
		return DD_FOR_TRACKS;
	}
}
